inkweb_module_homepage:
    path:     /modules/
    defaults: { _controller: InkwebModuleBundle:Module:index }
inkweb_module_view:
    path:     /modules/view/{id}
    defaults: { _controller: InkwebModuleBundle:Module:view }
inkweb_module_edit:
    path:     /modules/edit/{id}
    defaults: { _controller: InkwebModuleBundle:Module:edit }
inkweb_module_add:
    path:     /modules/add/{id}
    defaults: { _controller: InkwebModuleBundle:Module:addCours }

inkweb_cours_del:
    path:     /modules/del/{id}
    defaults: { _controller: InkwebModuleBundle:Module:delCours }

inkweb_module_addeval:
    path:     /modules/addeval/{id}
    defaults: { _controller: InkwebModuleBundle:Module:addEval }
inkweb_eval_view:
    path:     /modules/eval/view/{id}
    defaults: { _controller: InkwebModuleBundle:Module:viewEval }
inkweb_eval_del:
    path:     /modules/eval/del/{id}
    defaults: { _controller: InkwebModuleBundle:Module:delEval }
