inkweb_module_homepage:
    path:     /modules/
    defaults: { _controller: InkwebModuleBundle:Module:index }
inkweb_module_view:
    path:     /modules/view/{id}
    defaults: { _controller: InkwebModuleBundle:Module:view }
inkweb_module_add:
    path:     /modules/add/{id}
    defaults: { _controller: InkwebModuleBundle:Module:addCours }