inkweb_dashboard:
    resource: "@InkwebDashboardBundle/Resources/config/routing.yml"
    prefix:   /

inkweb_module:
    resource: "@InkwebModuleBundle/Resources/config/routing.yml"
    prefix:   /

inkweb_professeur:
    resource: "@InkwebProfesseurBundle/Resources/config/routing.yml"
    prefix:   /

inkweb_eleve:
    resource: "@InkwebEleveBundle/Resources/config/routing.yml"
    prefix:   /

inkweb_user:
    resource: "@InkwebUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin