# Affichage liste classe
inkweb_eleve_homepage:
    path:     /classe/
    defaults: { _controller: InkwebEleveBundle:Classe:index }

# Affichage liste des élèves par classe
inkweb_eleve_liste_classe:
    path:     /classe/id/{id}
    defaults: { _controller: InkwebEleveBundle:Classe:listclass}

# Affichage d'un élève
inkweb_eleve_view:
    path:     /eleve/view/{id}
    defaults: { _controller: InkwebEleveBundle:Eleve:view  }
