inkweb_eleve_homepage:
    path:     /eleve/
    defaults: { _controller: InkwebEleveBundle:Eleve:index }

inkweb_eleve_view:
    path:     /eleve/view/{id}
    defaults: { _controller: InkwebEleveBundle:Eleve:view  }

inkweb_eleve_edit:
    path:     /eleve/edit/{id}
    defaults: { _controller: InkwebEleveBundle:Eleve:edit  }

inkweb_classe_homepage:
    path:   /eleve/classe/
    defaults: { _controller: InkwebEleveBundle:Classe:index }

inkweb_classe_addMass:
    path:   /eleve/classe/addMass
    defaults: { _controller: InkwebEleveBundle:Classe:addMass }