<?php

namespace Inkweb\ModuleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository
{
    public function listCours($module){

        $queryBuilder = $this->createQueryBuilder('a');
        $date = new \DateTime();
        $queryBuilder
            ->where('a.module = :module')
                ->setParameter('module',$module)
            ->andWhere('a.date >= :date')
                ->setParameter('date',$date)
            ->orderBy('a.date','DESC')
            ->orderBy('a.heure','DESC')
            ;

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
