<?php

namespace Inkweb\ModuleBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Inkweb\EleveBundle\Entity\Classe;
use Inkweb\EleveBundle\Entity\Eleve;
use Inkweb\EleveBundle\InkwebEleveBundle;
use Inkweb\ModuleBundle\Entity\Module;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{

    // Affiche la liste des élèves inscrit à un module
    public function listEleveModule($module){

        $query = $this->_em->createQuery(
          'SELECT e
          FROM InkwebEleveBundle:Eleve e,
           InkwebEleveBundle:Classe c,
           InkwebModuleBundle:Module m
           WHERE e.classe = c.id
           AND m.id ='. $module .'
           AND m.classe = c.id'
        );

        $results = $query
            ->getResult();
        return $results;
    }
}
